### ISSUE TITLE
Help on how to handle animation repetition

### ISSUE THREAD

**Issue by malbernaz** [lerouxrgd/bevy_mod_aseprite#7]
I want some animations to only play once and stop on the last frame. Is it there a practical way of doing this with this library? Thanks in advance!

**Comment by lerouxrgd** [comment]
You could use something similar to:

https://github.com/lerouxrgd/bevy_mod_aseprite/blob/068a9a251ebf3515d78c1b71d3f5d6f93123db7a/examples/aseprite.rs#L177-L181

But instead of changing the state of your entity, that is `ev_player_changed.send(PlayerState::Stand.into())` here, you could remove its [Handle< Aseprite >](https://docs.rs/bevy_mod_aseprite/latest/bevy_mod_aseprite/struct.Aseprite.html) and [AsepriteAnimation](https://docs.rs/bevy_mod_aseprite/latest/bevy_mod_aseprite/struct.AsepriteAnimation.html) components.
